---
apiVersion: v1
kind: Service
metadata:
  name: simon-says-server
  labels:
    visualize: "true"
    name: server
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    role: simon-says-server
  type: LoadBalancer